# Generated by Django 5.0 on 2024-10-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(default='cash', max_length=50),
            preserve_default=False,
        ),
    ]
