# Generated by Django 5.0 on 2024-10-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryy', '0003_inventoryreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryReport',
        ),
    ]
